<?php $this->render('common/header'); ?>

<div class="page-header">
<?php if($evento): ?>
    <h1><strong><?=$pessoa->nome?></strong> - Editar evento: <?=$evento->descricao?></h1>
<?php else: ?>
    <h1>Novo evento para <strong><?=$pessoa->nome?></strong></h1>
<?php endif; ?>
</div>

<div class="row">
    <div class="col-md-6">
        <form action="<?=url()->route('eventos.salvar');?>" method="post" class="form-horizontal" role="form">
            <fieldset>

                <?php
                if($evento): ?>
                    <input type="hidden" name="id" value="<?=$evento->id;?>">
                <?php endif; ?>

                <input type="hidden" name="pessoa" value="<?=$pessoa->id;?>">

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Data</label>
                    <div class="col-sm-4">
                        <input name="data" type="text" placeholder="dd/mm/aaaa" class="form-control"
                          onkeypress="formata(this, '##/##/####');"      value="<?=$evento ? dt($evento->data)->format('d-m-Y') : '';?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Das</label>
                    <div class="col-sm-3">
                        <input name="hora_de" value="<?=$evento ? $evento->hora_de : '';?>" type="time"
                               placeholder="hh:mm" class="form-control">
                    </div>

                    <label class="col-sm-1 control-label" for="textinput">Às</label>
                    <div class="col-sm-3">
                        <input name="hora_ate" value="<?=$evento ? $evento->hora_ate : '';?>" type="time"
                               placeholder="hh:mm" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="textinput">Descrição</label>
                    <div class="col-sm-10">
                        <textarea name="descricao" placeholder="Descrição" class="form-control"><?=$evento ? $evento->descricao : '';?></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>
</div>
<script language="javascript">
<!--
function formata(src, mask)
//funcao para formatar qualquer campo.Ex.:cep,cpf,telefone,cnpj.
{
var i = src.value.length;
var saida = '#';
var texto = mask.substring(i)
if (texto.substring(0,1) != saida)
{
src.value += texto.substring(0,1);
}
}
-->
</script>

<a class="btn btn-info" href="<?=url()->route('eventos.index', ['pessoa' => $pessoa->id]);?>">Voltar</a>

<?php if(session()->has('_sucesso')): ?>
    <div class="alert alert-success" role="alert"><?=session()->getAndRemove('_sucesso');?></div>
<?php endif;  ?>

<?php if(session()->has('_erro')): ?>
    <div class="alert alert-warning" role="alert"><?=session()->getAndRemove('_erro');?></div>
<?php endif;  ?>


<?php $this->render('common/footer'); ?>

